### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [wjdrhkd456/springboot_and_aws_exam_project#1]
Hi,<br><br>url : https://github.com/wjdrhkd456/springboot_and_aws_exam_project/blob/d7b542fff395efea06c7ecb30e6e0f367ff895a2/src/main/resources/application-real-db.properties <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by wjdrhkd456** [comment]
Oh my god.. I really appreciated it.. Have a nice day! lol

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by shaybenb** [comment]
Hi 
you just can click on 
https://www.buymeacoffee.com/bugbounty
or
https://www.paypal.com/paypalme/bugbounty1
and buy beer :)  , its with Paypal...
